export const employeesData = [
  {
    id: 22086,
    skills: ['React.js', 'Angular 4', 'Angular 8', 'Node.js', 'docker'],
    name: 'Ashok',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 27899,
    skills: ['Angular 4', 'Angular 8', 'Node.js', 'Mongo Db'],
    name: 'Shailesh',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 98765,
    skills: ['Angular 4', 'Angular 8', 'Node.js'],
    name: 'Tapan',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 27865,
    skills: ['React.js', 'Angular 4', 'Angular 8', 'Node.js', 'docker'],
    name: 'Dipak',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 57890,
    skills: ['Mongo Db'],
    name: 'Himanshu',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 68989,
    skills: ['Java'],
    name: 'Vidush',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 71233,
    skills: ['.Net', 'Node.js', 'docker'],
    name: 'Deep',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 89876,
    skills: ['Angular 8', 'Node.js', 'Mongo Db'],
    name: 'Vishal',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 92345,
    skills: ['Angular 4', 'Angular 8', 'Node.js'],
    name: 'Jagdish',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 10235,
    skills: ['React.js', 'Node.js', 'docker'],
    name: 'Vivek',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 11098,
    skills: ['Kubernaes', 'Azure', 'Aws'],
    name: 'Gajanan',
    location: 'India Pune',
    country: 'India',
  },
  {
    id: 12876,
    skills: ['Angular 4', 'Angular 8', 'Node.js'],
    name: 'Dev',
    location: 'India Pune',
    country: 'India',
  },
];
